// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"time"
)

type Todo struct {
	ID        int64
	UserID    int64
	Title     string
	Completed bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
