// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: todos.sql

package db

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    user_id,
    title
) VALUES (
    $1,
    $2
)
RETURNING id, user_id, title, completed, created_at, updated_at
`

type CreateTodoParams struct {
	UserID int64
	Title  string
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.UserID, arg.Title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const deleteTodosByUser = `-- name: DeleteTodosByUser :exec
DELETE FROM todos
WHERE user_id = $1
`

func (q *Queries) DeleteTodosByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodosByUser, userID)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, user_id, title, completed, created_at, updated_at
FROM todos
WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncompleteTodosByUser = `-- name: ListIncompleteTodosByUser :many
SELECT id, user_id, title, completed, created_at, updated_at
FROM todos
WHERE user_id = $1
  AND completed = FALSE
ORDER BY id
`

func (q *Queries) ListIncompleteTodosByUser(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listIncompleteTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByUser = `-- name: ListTodosByUser :many
SELECT id, user_id, title, completed, created_at, updated_at
FROM todos
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) ListTodosByUser(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTodoCompleted = `-- name: SetTodoCompleted :one
UPDATE todos
SET
    completed = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, completed, created_at, updated_at
`

type SetTodoCompletedParams struct {
	ID        int64
	Completed bool
}

func (q *Queries) SetTodoCompleted(ctx context.Context, arg SetTodoCompletedParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, setTodoCompleted, arg.ID, arg.Completed)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoTitle = `-- name: UpdateTodoTitle :one
UPDATE todos
SET
    title = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, completed, created_at, updated_at
`

type UpdateTodoTitleParams struct {
	ID    int64
	Title string
}

func (q *Queries) UpdateTodoTitle(ctx context.Context, arg UpdateTodoTitleParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoTitle, arg.ID, arg.Title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
